# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0003_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNo', models.CharField(max_length=255)),
                ('permitNo', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ID_Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personIDParking', to='subApp1.Person')),
            ],
        ),
        migrations.RenameField(
            model_name='building',
            old_name='personID_from',
            new_name='ID_Building',
        ),
    ]
