# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0004_auto_20180528_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardType', models.CharField(max_length=255)),
                ('CardAmt', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ID_mealType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealTypeID', to='subApp1.userType')),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personMealID', to='subApp1.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='ID_Building',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='ID_Parking',
        ),
        migrations.AddField(
            model_name='building',
            name='ID_building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personBuildingID', to='subApp1.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='ID_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personParkingID', to='subApp1.Person'),
            preserve_default=False,
        ),
    ]
