# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0005_auto_20180528_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='person_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personGroupID', to='subApp1.Person'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='userType_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTypeID', to='subApp1.userType'),
        ),
    ]
