# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subApp1', '0006_auto_20180528_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='ID_person',
            new_name='ID_parking',
        ),
    ]
